### ISSUE TITLE
Disk set regeneration question

### ISSUE THREAD

**Issue by seal331** [mamccollum/svr4-386-src#2]
Hello there, and thanks for your work on preserving these old Unixen!

I've been wondering - how exactly did you pull off regenerating the distribution media for the useful packages from the source code? I've been able to regenerate the base set and the bootdisks, but AFAIK the PACKAGES.mk and csds.mk files are missing from this source dump, and that makes regenerating the other sets impossible to regenerate. I suspect it has something to do with the add-on/ directory, but I've been unable to figure out how to turn the files from there into actual usable sets, and :mk.addon spits out errors such as "`<insert package name here>.mk not found`" errors when I try to run that.

Thanks in advance!

**Comment by mamccollum** [comment]
I had to enter each package directory that contained a file named `prototype`, then run `pkgmk -d diskette1`.

An example of one of the directories would be: `usr/src/add-on/pkg.edit` for the `vi` program.

You can `cd` to there and then run that `pkgmk -d diskette1` command which will create the package and spit it out onto the floppy. It will prompt you to format the diskette first, which you must do. It may ask for multiple floppies -- just insert the next and format and then type `go` until it's done.

I  would like to note that the SCDE C development floppies fail to copy `term.h` on floppy 4/5 I believe. Just put it on its own floppy -- it will still install without term.h, but it will say it "failed" (it really only mails root.) and you can `mount /install` to mount the floppy if you so wish to keep that term.h.

Also with the unlimited user license, I believe you need to cd to `usr/src/proto/i386/PACKAGES/peruser` and run `make -f peruser.mk`.

If this helps, let me know and close this issue. If not, reply and I should get back to you in a hopefully short amount of time.

P.S: I also managed to get DNS and NFS working with a real machine on my LAN. If you want some pointers, you can make another GitHub issue and I can document what I know in the comments.

**Comment by seal331** [comment]
While I was not able to get `pkgmk -d diskette1` to work, `pkgmk -d /dev/dsk/f03ht` did the job! Thank you, now it's time to spend some time swapping floppies around to get the entire thing written to floppies :)
